name: theAutomaticDev

on:
  push:
    branches: [ master ]

jobs:
#  laravel-tests:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Copy .env
#        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
#      - name: Install Dependencies
#        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
#      - name: Generate key
#        run: php artisan key:generate
#      - name: Directory Permissions
#        run: chmod -R 777 storage bootstrap/cache
#      - name: Create Database
#        run: |
#          mkdir -p database
#          touch database/database.mysql
#      - name: Execute tests (Unit and Feature tests) via Pest
#        env:
#          DB_CONNECTION: mysql
#          DB_DATABASE: database/database.mysql
#        run: vendor/bin/pest


#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Setup Node.js
#        uses: actions/setup-node@v2-beta
#        with:
#          node-version: '12'
#          check-latest: true
#      - name: Install NPM dependencies
#        run: npm install
#      - name: Compile assets for production
#        run: npm run production

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSHKEY }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd /var/www/theautomatic.dev
            sudo chown -R www-data:www-data /var/www/theautomatic.dev
            php artisan down
            sudo git fetch origin master
            sudo git reset --hard origin/master
            sudo chgrp -R www-data storage bootstrap/cache
            sudo chmod -R ug+rwx storage bootstrap/cache
            composer install --no-interaction --prefer-dist --optimize-autoloader
            composer update
            npm install
            npm run build
            php artisan migrate --force
            php artisan optimize
            php artisan up
